module.exports = {
	TOOLBAR: 'TOOLBAR',
	BREADCRUMBS: 'BREADCRUMBS',
	VERTICAL_SCROLLER: 'VERTICAL_SCROLLER',
	SEARCH_BAR: 'SEARCH_BAR',
	TITLE_TEXT: 'TITLE_TEXT',
	TEXT: 'TEXT',
	IMAGE: 'IMAGE',
	CODE_SNIPPET: 'CODE_SNIPPET',
	MARKDOWN: 'MARKDOWN',
	LINK: 'LINK',
	ARTICLE_CONTENT: 'ARTICLE_CONTENT',
	FOOTER: 'FOOTER',
	ARTICLE_LINK: 'ARTICLE_LINK',
	DETAIL_CARD: 'DETAIL_CARD'
}
